name: tests

on:
    push:
    pull_request:

jobs:
    tests:
        name: run all unit tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install dependencies
                run: composer update
            -   name: Execute tests
                run: composer test
